### ISSUE TITLE
Copy client config to clipboard - help to troubleshoot

### ISSUE THREAD

**Issue by jcoffland** [FoldingAtHome/fah-control#3]
**Reported by @7im- on 4 Aug 2010 16:02 UTC**
Please consider adding a button that copies the currently selected client's config.xml file contents to the clipboard in Windows (minus the passkey, if possible).

This would be very helpful for new users trying to seek help on the folding forum.  We often ask for a copy of their config file to help us diagnose issues.

Thanks.

**Comment by jcoffland** [comment]
**Comment by @jcoffland on 4 Aug 2010 19:37 UTC**
OK, that is possible.  It would take a bit of work and is a fairly low priority so I don't see it happening soon.

At the default verbosity (2) the '''config.xml''' is printed to the log with out the passkey so you could instruct them to copy and paste it from there.

**Comment by shorttack** [comment]
> jcoffland pushed a commit that referenced this issue on May 9, 2018
closed: ancient
