### ISSUE TITLE
FahControl 7.5.0 beta for Windows theme libs missing

### ISSUE THREAD

**Issue by informatorius** [FoldingAtHome/fah-control#30]
In FahControl 7.5.0 beta for Windows the theme libs are missing.
C:\Program Files (x86)\FAHClient\[**lib\gtk-2.0\2.10.0\engines**]MISSING

When I manually copy the dlls from FahClient 7.4.16 then the themes are fully working again.

Without the dlls the icons and images are not loaded on Windows and the themes look flat and colors and 3D effects missing. Also reported here by toTOW
https://foldingforum.org/viewtopic.php?f=104&t=30789&start=15#p301384

**Comment by jcoffland** [comment]
Notice the theme DLLs are actually all in ``C:\Program Files (x86)\FAHClient\`` but I suppose that does not cut it.

**Comment by jcoffland** [comment]
For me the themes seem to work fine with out fixing the engine directory.  How can I tell if it's fixed?  Can you provide screenshots of the good and bad.

**Comment by jcoffland** [comment]
Nevermind, I figured it out.  ``Clearlooks Vista`` has white text on a white background for selected dropdown items when the theme engine is missing.

**Comment by informatorius** [comment]
Solved with Fah 7.5.1 beta
