### ISSUE TITLE
keeps my pc from going into energy saving mode (when paused/finished)

### ISSUE THREAD

**Issue by Djfe** [FoldingAtHome/fah-control#35]
If the folding@home app is running in the tray but doesn't fold, then it still keeps my pc from going into energy saving mode (even if I start energy saving manually from the start menu).

**Comment by shorttack** [comment]
More information needed, please:
1. OS and version
2. What is the status of the app? Waiting for work? Paused? Folding?

As a workaround, try Pausing FAHcontrol (the app). Or move the slider left from Full to Minimum. At minimum, the client only runs on OS idle cycles and should allow an energy-saving sleep. If that does not allow energy savings, you'll have to quit the app. 

Normally, when you're folding, the app runs all the time and there's no opportunity for OS energy savings. 

For more support, try the support at [https://foldingforum.org/index.php](url). All they do is support users like you.

**Comment by shorttack** [comment]
closed: ancient
