### ISSUE TITLE
PPD

### ISSUE THREAD

**Issue by chabgood** [FoldingAtHome/fah-control#40]
Is it possible to get the PPD from the cli?

**Comment by bb30994** [comment]
Calculate the progress of the WU and the time that has passed to estimate the total time to complete the WU.  Divide 24 hours by that projected time to estimate the number of WUs from that project can be completed in a day.  Multiply the baseline points by the number of WUs per day to get the baseline PPD.  Using the traditional formula for bonus points, calculate the bonus and add it to get the total PPD.
