### ISSUE TITLE
Increase compression WUs and completed WUs before transmitting over internet

### ISSUE THREAD

**Issue by ProDigit** [FoldingAtHome/fah-control#41]
With faster hardware, it's perhaps a good idea to have the client handle higher compression data.
Current RTX WUs are ~25-70MB, and each card processes about 5-10 per day.
That's ~200-400MB per card.

Daily traffic is quite high, since I run multiple cards (9 currently, and I'm hovering around a few gigabytes of WUs per day, just for FAH).

Since large WUs affects mostly GPU servers, and they often run GPUs only, the CPU resources could be used to compress the data.

At <70MB per WU, it should take under 30 seconds to compress a WU, so it shouldn't affect performance that much; but it should lower bandwidth for larger servers.

Thanks

**Comment by bb30994** [comment]
In many older versions of FAHClient, the WUs were compressed.  As some point they were converted to man-readable form which really should be compressed.

BTW, compression/uncompression would happen in FAHClient, not in FAHControl as well as on the servers.

**Comment by jcoffland** [comment]
This is does not apply to FAHControl.
