### ISSUE TITLE
no GPU detected

### ISSUE THREAD

**Issue by Borda** [FoldingAtHome/fah-control#45]
I am wondering how can I add also GPU, I have tried the default (recommended) setting but got
```
ERROR: On client "local" 127.0.0.1:36330: No available GPUs
```
and this my sys:
```
$ nvidia-smi
Thu Mar 12 21:46:14 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 435.21       Driver Version: 435.21       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1050    Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   71C    P0    N/A /  N/A |    489MiB /  4042MiB |      2%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1352      G   /usr/lib/xorg/Xorg                           239MiB |
|    0      3465      G   ...uest-channel-token=16720316923903381419    29MiB |
|    0      3987      G   ...AAAAAAAAAAAAAAgAAAAAAAAA --shared-files   178MiB |
+-----------------------------------------------------------------------------+
```

**Comment by informatorius** [comment]
FAHclient uses OpenCL on GPUs. OpenCL libs installed?

**Comment by Borda** [comment]
is it this OpenCL? https://streamhpc.com/blog/2011-06-24/install-opencl-on-debianubuntu-orderly/
or how can I check if I have it... searching in synaptic :]
BTW, it may be useful to extend the message so to say that user need the OpenCL

**Comment by informatorius** [comment]
sudo apt-get install ocl-icd-libopencl1
sudo apt-get install ocl-icd-opencl-dev

**Comment by Borda** [comment]
yeas, I did now but probably need a restart...

**Comment by informatorius** [comment]
> it may be useful to extend the message so to say that user need the OpenCL
Yes! And FAHclient installer should download that dependency automatically.

**Comment by bb30994** [comment]
The client needs some improvements in it's messages.

An AMD GPU gets an (unnecessary) error message saying it can't find CUDA.

Missing OpenCL (or the Microsoft OpenCL dll which doesn't work) produce a variety of unhelpful messages.  (These may already be listed on other tickets.)

**Comment by bb30994** [comment]
Yes, the Linux installer should manage the dependency.  When the Windows user manually installs drivers directly from NVidia, they automatically get OpenCL.  When WindowsUpdate delivers new drivers, MS automatically **_uninstalls_** NVidia's OpenCL

**Comment by Borda** [comment]
I am also getting following error:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/fah/Client.py", line 352, in update
    self.process_message(app, type, data)
  File "/usr/lib/python2.7/dist-packages/fah/Client.py", line 336, in process_message
    elif type == 'units': self.process_units(app, data)
  File "/usr/lib/python2.7/dist-packages/fah/Client.py", line 287, in process_units
    if self.selected: self.config.update_status_ui(app)
  File "/usr/lib/python2.7/dist-packages/fah/ClientConfig.py", line 534, in update_status_ui
    self.update_status_slots(app)
  File "/usr/lib/python2.7/dist-packages/fah/ClientConfig.py", line 435, in update_status_slots
    app.slot_status_tree.get_selection().select_iter(selected_row)
TypeError: iter should be a GtkTreeIter
ERROR: On client "local" 127.0.0.1:36330: No available GPUs
```

**Comment by informatorius** [comment]
This is a bug in FAHControl which does not detect your GPU yet but you added it manually using config file change. So removing it from config file repairs FAHcontrol.

**Comment by RoundRobin2** [comment]
Have you tried importing the Gpu list. and then trying to add the gpu slot.

`
wget https://fah-web.stanford.edu/file-releases/public/GPUs.txt
sudo mv GPUs.txt /var/lib/fahclient/
sudo service FAHClient restart
`

**Comment by Borda** [comment]
well it helped, but somehow with the Medium usage it takes 100% GPU which is not nice and if I make it as low it does not start because the external monitor takes 7% which means it is not idle...

**Comment by informatorius** [comment]
You can limit GPU power usage with tools like MSI Afterburner on Windows but FAH will always use full GPU or no GPU.

**Comment by Borda** [comment]
it turned out that with two slots (one for CPU and one for GPU) active and running Medium level it completely freezes computer and with the Lower level it does not use GPU at all... so I ma dropping GPU slot 8-]

**Comment by informatorius** [comment]
Then it is a hardware issue of GPU or power supply or cooling which leads to freeze.
