### ISSUE TITLE
python-gnome2 no longer available on debian, deb won't install

### ISSUE THREAD

**Issue by nilsjha** [FoldingAtHome/fah-control#46]
Dear developers,

Can you please update the package dependencies for the .deb package ? From Debian Stable (buster) and onward the package ```python-gnome2```, is no longer available in the package repositories.

https://tracker.debian.org/pkg/gnome-python
https://packages.debian.org/stretch/python-gnome2-dev

**Comment by agrrajag** [comment]
Same thing with Ubuntu 19.10.

**Comment by ariedov** [comment]
As a workaround:
`sudo dpkg -i --ignore-depends=python-gnome2 fahcontrol_7.4.4-1_all.deb`

**Comment by Seltonu** [comment]
Bump. I've switched to Rosetta@Home in the meantime because of this specific issue, Pop!_OS (Ubuntu) 19.10

**Comment by shorttack** [comment]
Please try the Linux beta at https://foldingathome.org/beta/

**Comment by Seltonu** [comment]
Confirming that the beta version fixes this issue, and installs without issue on Pop!_OS 19.10 (via Eddy)

**Comment by ariedov** [comment]
Can confirm the issue is resolved on Ubuntu 19.10

**Comment by ignaciocaamanio** [comment]
> Please try the Linux beta at https://foldingathome.org/beta/

Hi! I use archlinux. Is there a generic way of installing this Linux beta? thanks.

**Comment by shorttack** [comment]
@ignaciocaamanio There are install guides and many people who can assist a Linux install. Join the community at [https://foldingforum.org/index.php](url)

Closed: two worksforme above
_Issue Support_
