### ISSUE TITLE
Project link under Selected Work Unit does nothing when clicked

### ISSUE THREAD

**Issue by waded** [FoldingAtHome/fah-control#48]
The project link in FAHControl, shown in screenshot with label "14328" here:

![image](https://user-images.githubusercontent.com/1535656/76801922-35990000-679c-11ea-834c-9b51f75309a9.png)

does nothing when clicked. The right-click option, "Copy URL", seems to copy nothing if chosen.

Expected click to open default web browser to, in the case of 14328, https://apps.foldingathome.org/project?p=14328.

Version was 7.5.1 for Windows, the latest currently available from https://foldingathome.org/start-folding/ as of March 16 2020.

It appears this is possibly fixed in 7.5.2 98d6ba25c34d2c8f0dfcc3877b8622e3205e4253. That fix commit was in 2018. Some release tracking/drumbeat may be needed to get these fixes out.

**Comment by ipkh** [comment]
Please bear in mind there is a delay in getting new project web pages up.
In addition, currently the servers are being overloaded with requests.  All these minor issues should be resolved in the near future as more server power is brought online.

**Comment by asmaloney** [comment]
Thank you - but neither of those are the issue here. This is a bug and was happening before "all this" started.

The "right-click, Copy URL" that works for the identity links does not even copy a link for the project.

**Comment by psmlbhor** [comment]
I would like to contribute by fixing this issue. I can't find the mailing-list address or new devs guide.

**Comment by waded** [comment]
> I would like to contribute by fixing this issue. I can't find the mailing-list address or new devs guide.

As best I can tell it has been fixed (see commit in description) but binaries containing the fix are not released. May be best to offer help with release process & build automation above all else, then the fixes can start flowing and repeat bug reports will slow.

**Comment by ahoyJS** [comment]
This has been an issue in the past already. Apparently fixed, then broken again. 
https://github.com/FoldingAtHome/fah-issues/issues/1237
By the way, this bug is also present in the current Debian/Ubuntu version.

**Comment by shorttack** [comment]
FAHControl bug. May be fixed in 7.5.2 per #1237. Check in 7.6.x

**Comment by ipkh** [comment]
Confirmed fixed in 7.6.6 beta client 
foldingathome.org/beta/ on Xubuntu 18.04
Presumed fixed on all OS.

**Comment by shorttack** [comment]
> Confirmed fixed in 7.6.6 beta client

**Comment by waded** [comment]
I can confirm the fix (version 7.6.8.) The project link button launches web browser to the project page as expected.
