### ISSUE TITLE
Control of web-server access

### ISSUE THREAD

**Issue by ashh87** [FoldingAtHome/fah-control#52]
When trying to allow http server access from remote machines, FAHControl writes the following to config.xml:

```
<!-- HTTP Server -->
<allow v='0.0.0.0/0'/>
<deny v=''/>
```

This doesn't allow remote access to the http server. Searching the strings of FAHClient, I found 'web-allow'. Changing to the following got web access working for me:

```
<!-- HTTP Server -->
<allow v='0.0.0.0/0'/>
<web-allow v='0.0.0.0/0'/>
<deny v=''/>
```

There is probably a deny equivalent and this let me in with no password. Should FAHControl be updated to use 'web-allow' instead of/along with 'allow'?

**Comment by ashh87** [comment]
Since using FAHControl has sabed my config again, I now get this:

  
  <web-allow v='0.0.0.0/0'/>


so it must know about this option already. How to enable it from the UI in the first place?

**Comment by jcoffland** [comment]
This is does not apply to FAHControl.  You probably need to open your firewall to allow access to the port on FAHClient.
