### ISSUE TITLE
Python 3 + gtk 3

### ISSUE THREAD

**Issue by informatorius** [FoldingAtHome/fah-control#53]
If we move to Python 3 does it also need gtk 3?
https://developer.gnome.org/gtk3/stable/migrating.html

**Comment by ipkh** [comment]
Yes, it needs to move to gtk3.
The APIs used need to be updated to what Ubuntu 20.04 LTS will be using.
Same for Fedora and the other main distributions.

**Comment by nikolaik** [comment]
I've started on this in #56

**Comment by shorttack** [comment]
Please try the Linux beta at [](https://foldingathome.org/beta/) and report back here. Thanks.
_Issue Support_
