### ISSUE TITLE
Could not find suitable distribution for gtk2

### ISSUE THREAD

**Issue by sanjeevmk** [FoldingAtHome/fah-control#57]
I downloaded the repo and ran setup.py and got the following error:

Searching for gtk2>=2.14.0
Reading https://pypi.org/simple/gtk2/
Couldn't find index page for 'gtk2' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
No local packages or working download links found for gtk2>=2.14.0
error: Could not find suitable distribution for Requirement.parse('gtk2>=2.14.0')

Any idea how to resolve this?

**Comment by ipkh** [comment]
This is a known issue and is being worked on in a separate thread.
For assistance in this matter please provide some more information such as distribution and drivers.

Example:  Xubuntu 18.04.3
               linux 5.3 with Hardware Enablement Stack
               nvidia proprietary drivers.

**Comment by shorttack** [comment]
Please try the Linux beta at [https://foldingathome.org/beta/](url) and report back here. Thanks.
_Issue Support_

**Comment by shorttack** [comment]
Closed. Fixed #1318 in 7.6
