### ISSUE TITLE
work queue download progress stuck at 0%

### ISSUE THREAD

**Issue by michaelpalumbo** [FoldingAtHome/fah-control#58]
Hi there, my download status is stuck at 0%. 

my system info:

Intel core i7-7820HQ 2.9GHz
8 cpus
16GB memory, ~14gb free
Mac OSX version 10.12

**Comment by jhitze** [comment]
@michaelpalumbo Sometimes I've found that the process gets stuck trying to talk to assignment/work servers that may not be online at that moment. So restarting the underlying program gives a chance to wake up.

**Easy Version:**
Restart your computer

**Advanced version:**
Find the PID of `FAHClient` and run the following in you terminal:
```
sudo kill -HUP [PID that you found earlier]
```

**Comment by ipkh** [comment]
Recommend using sudo systemctl restart Fahclient 
Instead.

**Comment by shorttack** [comment]
Closed: workaround of present heavy comms traffic.
