### ISSUE TITLE
python-gtk2 not installable on ubuntu 20.04

### ISSUE THREAD

**Issue by PokefanSean** [FoldingAtHome/fah-control#65]
`Reading package list... Done
Building dependency  tree
Reading state information... Done
Package python-gtk2 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Unable to locate package python-gtk2`

**Comment by bhack** [comment]
See https://github.com/FoldingAtHome/fah-control/pull/56
