### ISSUE TITLE
Broken links in FAQ Overclocking section

### ISSUE THREAD

**Issue by jxramos** [FoldingAtHome/fah-control#66]
Clicking on some of the suggested links to tools in the overclocking section doesn't seem to work

https://foldingathome.org/support/faq/rules-policies/#overclocking

eg 

StressCPU ==> https://foldingathome.org/start-folding#ntoc1
MemtestG80 ==> https://foldingathome.org/start-folding/#ntoc2
MemtestCL ==> https://foldingathome.org/start-folding/#ntoc2

**Comment by shorttack** [comment]
Sorry, you'll have to take that up at foldingforum.org. We can't help you here.
