### ISSUE TITLE
Introduce progress bar for other statuses

### ISSUE THREAD

**Issue by jxramos** [FoldingAtHome/fah-control#67]
The download and upload status states should likewise contribute to the progress bar. There's a bit of confusion to see progress 100% while there's an active operation taking place that can take tens of seconds or more to complete.

Basically the same information we find in the log would be great to have represented in the progress bar in the client.
```
04:23:15:WU02:FS01:Upload 50.40%
04:23:21:WU02:FS01:Upload 52.30%
04:23:27:WU02:FS01:Upload 54.74%
04:23:33:WU02:FS01:Upload 57.17%
04:23:39:WU02:FS01:Upload 59.07%
04:23:45:WU02:FS01:Upload 61.51%
04:23:51:WU02:FS01:Upload 63.68%
```
Right now the progress bar seems to be owned by the `Running` status state, let's generalize it for the other operations which though relatively shorter than Running are not instant operations.

Another UI idea is to have the first progress bar used for the download operation, then that progress bar gets reused for running. Then a second progress bar beneath the completed running progress bar, with a different color perhaps, would become visible and be used for the upload operation.

**Comment by shorttack** [comment]
This is not a bug. When the next-unit-percentage is hit, you will see a new bar that depicts the download while that happens. You are correct, the upload is not shown, but running is shown.
