### ISSUE TITLE
CPU slot gets added back in without me telling it to do so

### ISSUE THREAD

**Issue by FlorinAndrei** [FoldingAtHome/fah-control#68]
macOS 10.15.4
FAH 7.5.1

I've installed it on the Mac just for the control app. I am folding on other systems. I just launch FAHControl here to keep an eye on the actual folding systems.

So I removed all slots from this system - actually, it only had a CPU slot, which I removed.

Then I used the app to control the other folding machines.

Today, I left the Mac sitting idle for a while, when I heard the fans speeding up. Sure enough, it was folding. I checked the config, and the CPU slot was somehow added back in. I didn't tell it to do that.

Why is the slot added automatically? I want to keep this machine at zero slots.

**Comment by shorttack** [comment]
The FAHControl app was not designed to run remote instances while not doing any folding. What you need is [https://github.com/harlam357/hfm-net](url) HFM runs on Windows (or Wine on Linux) or Parallels on Mac. HFM is specifically designed to monitor remote folding clients. You can also find help at folding forum -- [https://foldingforum.org/index.php](url) Good luck.
_Issue Support_

**Comment by FlorinAndrei** [comment]
I just paused the CPU slot on the Mac and it stays paused. Good enough.
