### ISSUE TITLE
Monitoring API change or issue ?

### ISSUE THREAD

**Issue by Adanorm** [FoldingAtHome/fah-control#69]
Hello,

I'm testing the fahclient 7.6.0.
Some issues on monitoring side, I have developped a web layer based on HFM.net exports. 
Some data are not reported. Does something has been removed on API ?

My web app : http://fahmon.fleucorp.net/ 

Missing data (for the moment what we saw) :
- Client Version
- Username
- Team ID
- Slot Type (GPU are reported as CPU)

Harlam has been contacted too. https://github.com/harlam357/hfm-net/issues/304

**Comment by Adanorm** [comment]
Tested with 7.6.2, no improvement.

**Comment by Adanorm** [comment]
Hello,

Lot of fixes with 7.6.6 beta. By the way there is maybe a last missing data : ClientVersion

**Comment by shorttack** [comment]
@Adanorm Please keep adding testing feedback here on this issue, asharlam357 and the team here are aware HFM got broken with 7.6.
_Issue Support Team_

**Comment by Adanorm** [comment]
Hello,

7.6.7 ClientVersion still missing.

**Comment by Adanorm** [comment]
Hello,

Same with 7.6.8

**Comment by harlam357** [comment]
After talking with the FAHClient developer and looking at the way the data changed, we decided that I would handle the ClientVersion issue on the HFM side. Suggest closing this issue here since it's not directly related to FAHControl.

**Comment by shorttack** [comment]
> Suggest closing this issue here since it's not directly related to FAHControl.

Closed: wontfix because Harlam357 is fixing it in HFM.Net.
