### ISSUE TITLE
Option to cancel workunit

### ISSUE THREAD

**Issue by margin-auto** [FoldingAtHome/fah-control#73]
An option in the client to cancel and reject an already downloaded and maybe also started workunit would be great. In case the user has some technical problems or decides to stop folding (on this machine), there is no way to tell the server that there will be no result for this WU so he has to wait until the WU expires to assign it to a new client. If the client could tell the server that the WU will not be finished, the server could re-assign it to a new user immediately and no time is wasted.

**Comment by PantherX** [comment]
Please note that there won't be an easy GUI way to do that since it will be abused to only fold WUs that will result in high points. This would only encourage cherry-picking which is not allowed by F@H.

**Comment by margin-auto** [comment]
Thanks for your explanation, I hadn't that in mind. Are there any statistics avaliable how many WUs aren't finished and returned tuthe servers? So that one could judge how big this problem is. Or if it isn't a problem at all.

**Comment by PantherX** [comment]
Assuming you're using a passkey, then you can see your percentage of returned WUs: https://apps.foldingathome.org/bonus
You can also have a total overview of how many WUs are available here:
https://apps.foldingathome.org/serverstats
