### ISSUE TITLE
Ubuntu 20.04 python2 problem

### ISSUE THREAD

**Issue by denisafanasev** [FoldingAtHome/fah-control#78]
Due to there is no python 2 in Ubuntu 20.04 the FAHControl doesn't install on that OS:

After 

**_sudo dpkg -i --force-depends fahcontrol_7.6.9-1_all.deb_**

got an error

fahcontrol depends on python-gtk2 | python-gnome2; however:
Package python-gtk2 is not installed.
Package python-gnome2 is not installed.

and also there is no python-gnome2 available by:

**_sudo apt-get install -y python-stdeb python-gtk2 python-all debhelper_**

Package python-stdeb is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  python3-stdeb

E: Package 'python-stdeb' has no installation candidate
E: Unable to locate package python-gtk2

Suppose the moving to python3 is necessary.

**Comment by benkean** [comment]
#55 #56 #70

**Comment by cdberkstresser** [comment]
@denisafanasev  We do have rpms and debs for PR #70, which is definitely a work in progress.  It is what I've used to do the beta testing for FAHClient from Ubuntu 20.04 when I needed FAHControl to see what was going on.
https://github.com/cdberkstresser/fah-control/releases

**Comment by denisafanasev** [comment]
Thank you very much! Looking forward for a new release!

**Comment by PSLLSP** [comment]
It is April 2022. FAHcontrol still doesn't work in Ubuntu 20.04. Ubuntu 22.04 was released this week... :-(
