### ISSUE TITLE
Which University?

### ISSUE THREAD

**Issue by bb30994** [FoldingAtHome/fah-control#80]
> A trivial issue: The 'About' window for FAH Client Control credits Gregory Bowman at Washington _State_ University in Saint Louis, but the university name is Washington University in Saint Louis. It's a minor point but worth fixing.

**Comment by cdberkstresser** [comment]
@bb30994 I've added this update to PR #70 .

**Comment by ffissore** [comment]
Fixed in 3189958e4ea40516dc2956a4d6b1797ff75acd02
