### ISSUE TITLE
Finish button does not work in web control

### ISSUE THREAD

**Issue by zunyangtan** [FoldingAtHome/fah-control#83]
https://client.foldingathome.org/
Button at [Stop Folding -> Finish Up] does not send job status to finishing.
Using fahclient_7.6.13_amd64.deb in Ubuntu 20.04.

**Comment by PantherX** [comment]
Hiya,
Please note that this is a known issue: https://github.com/FoldingAtHome/fah-issues/issues/1415

I will not be closing this as a duplicate :)
