### ISSUE TITLE
FAHControl doesn't open on macOS 11

### ISSUE THREAD

**Issue by ajs256** [FoldingAtHome/fah-control#88]
Title. It doesn't show any errors when I run it from the command line. I am on macOS 11.0.1 and FaH version 7.6.21. Please tell me what you need from me to help with this.

**Comment by PantherX** [comment]
Hiya @ajs256 

Please note that this has been raised here: https://github.com/FoldingAtHome/fah-issues/issues/1576 so will close this one.
