### ISSUE TITLE
Restore slots

### ISSUE THREAD

**Issue by watmm** [FoldingAtHome/fah-control#95]
Hi all.

I deleted the suggested slots in an attempt to get it to only use my GPU. 
Now i'm wondering how to restore it to the originally suggested slots and slot options.
Reinstalling doesn't help. Any ideas?

It was cdberkstresser's port but that's probably unrelated.

Cheers.

**Comment by kbernhagen** [comment]
Please ask for help on https://foldingforum.org/

**Comment by cdberkstresser** [comment]
@watmm It's been a while since I looked at this project, but I believe the config file is "owned" by fahclient and not fahcontrol (even though fahcontrol offers some editing tools).  If you are comfortable with reinstalling, do so with fahclient and not fahcontrol.
